---
#
# Ansible managed
#
repository:
  description: Install the Enpass password manager on your system.
  homepage: https://robertdebock.nl/
  topics: enpass, password-manager, ansible, molecule, tox, playbook, hacktoberfest
