---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Get status of /opt/enpass/Enpass
      ansible.builtin.stat:
        path: /opt/enpass/Enpass
      register: enpass_veriy_binary
      failed_when:
        - not enpass_veriy_binary.stat.exists
